name = "sociobot-telegram-bot1-prod"
main = "src/worker.js"
compatibility_date = "2024-08-29"

[vars]
TELEGRAM_BOT_TOKEN = "TU_TOKEN_DE_TELEGRAM"
RETELL_API_KEY = "TU_API_KEY_RETELL"
QUEUE_NAME = "agents-queue"
